#!/bin/bash


# Params:
# $1 file to read
# $2 output kmd file


export PATH=$PATH:/data/toolchains/bin

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd ) 
cd $SCRIPT_DIR

OUTPUT=$(python3 elftokmd.py $1)

echo -e "$OUTPUT" > $2